services:
  db:
    networks:
      - shared_network
    image: postgres:latest
    container_name: "postgresdb"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
    driver: local