// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: optimizer/optimizer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListIndexesStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListIndexesStatRequest) Reset() {
	*x = ListIndexesStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optimizer_optimizer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIndexesStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesStatRequest) ProtoMessage() {}

func (x *ListIndexesStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_optimizer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesStatRequest.ProtoReflect.Descriptor instead.
func (*ListIndexesStatRequest) Descriptor() ([]byte, []int) {
	return file_optimizer_optimizer_proto_rawDescGZIP(), []int{0}
}

type ListIndexesStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexesStat []*ListIndexesStatResponse_IndexStat `protobuf:"bytes,1,rep,name=indexes_stat,json=indexesStat,proto3" json:"indexes_stat,omitempty"`
}

func (x *ListIndexesStatResponse) Reset() {
	*x = ListIndexesStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optimizer_optimizer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIndexesStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesStatResponse) ProtoMessage() {}

func (x *ListIndexesStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_optimizer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesStatResponse.ProtoReflect.Descriptor instead.
func (*ListIndexesStatResponse) Descriptor() ([]byte, []int) {
	return file_optimizer_optimizer_proto_rawDescGZIP(), []int{1}
}

func (x *ListIndexesStatResponse) GetIndexesStat() []*ListIndexesStatResponse_IndexStat {
	if x != nil {
		return x.IndexesStat
	}
	return nil
}

type ListIndexesStatResponse_IndexStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName     string  `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	IndexName     string  `protobuf:"bytes,2,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	IndexScans    float32 `protobuf:"fixed32,3,opt,name=index_scans,json=indexScans,proto3" json:"index_scans,omitempty"`
	TuplesRead    float32 `protobuf:"fixed32,4,opt,name=tuples_read,json=tuplesRead,proto3" json:"tuples_read,omitempty"`
	TuplesFetched float32 `protobuf:"fixed32,5,opt,name=tuples_fetched,json=tuplesFetched,proto3" json:"tuples_fetched,omitempty"`
}

func (x *ListIndexesStatResponse_IndexStat) Reset() {
	*x = ListIndexesStatResponse_IndexStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optimizer_optimizer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIndexesStatResponse_IndexStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesStatResponse_IndexStat) ProtoMessage() {}

func (x *ListIndexesStatResponse_IndexStat) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_optimizer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesStatResponse_IndexStat.ProtoReflect.Descriptor instead.
func (*ListIndexesStatResponse_IndexStat) Descriptor() ([]byte, []int) {
	return file_optimizer_optimizer_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListIndexesStatResponse_IndexStat) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ListIndexesStatResponse_IndexStat) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *ListIndexesStatResponse_IndexStat) GetIndexScans() float32 {
	if x != nil {
		return x.IndexScans
	}
	return 0
}

func (x *ListIndexesStatResponse_IndexStat) GetTuplesRead() float32 {
	if x != nil {
		return x.TuplesRead
	}
	return 0
}

func (x *ListIndexesStatResponse_IndexStat) GetTuplesFetched() float32 {
	if x != nil {
		return x.TuplesFetched
	}
	return 0
}

var File_optimizer_optimizer_proto protoreflect.FileDescriptor

var file_optimizer_optimizer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x69,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x18, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa6, 0x02, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x0c, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61, 0x74, 0x52, 0x0b,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x1a, 0xb2, 0x01, 0x0a, 0x09,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x74, 0x61, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x5f, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x75, 0x70, 0x6c,
	0x65, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x74,
	0x75, 0x70, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x75, 0x70,
	0x6c, 0x65, 0x73, 0x5f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0d, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x46, 0x65, 0x74, 0x63, 0x68, 0x65, 0x64,
	0x32, 0x76, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x41, 0x50, 0x49,
	0x12, 0x66, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69,
	0x7a, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_optimizer_optimizer_proto_rawDescOnce sync.Once
	file_optimizer_optimizer_proto_rawDescData = file_optimizer_optimizer_proto_rawDesc
)

func file_optimizer_optimizer_proto_rawDescGZIP() []byte {
	file_optimizer_optimizer_proto_rawDescOnce.Do(func() {
		file_optimizer_optimizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_optimizer_optimizer_proto_rawDescData)
	})
	return file_optimizer_optimizer_proto_rawDescData
}

var file_optimizer_optimizer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_optimizer_optimizer_proto_goTypes = []interface{}{
	(*ListIndexesStatRequest)(nil),            // 0: api.optimizer.v1.ListIndexesStatRequest
	(*ListIndexesStatResponse)(nil),           // 1: api.optimizer.v1.ListIndexesStatResponse
	(*ListIndexesStatResponse_IndexStat)(nil), // 2: api.optimizer.v1.ListIndexesStatResponse.IndexStat
}
var file_optimizer_optimizer_proto_depIdxs = []int32{
	2, // 0: api.optimizer.v1.ListIndexesStatResponse.indexes_stat:type_name -> api.optimizer.v1.ListIndexesStatResponse.IndexStat
	0, // 1: api.optimizer.v1.OptimizerAPI.ListIndexesStat:input_type -> api.optimizer.v1.ListIndexesStatRequest
	1, // 2: api.optimizer.v1.OptimizerAPI.ListIndexesStat:output_type -> api.optimizer.v1.ListIndexesStatResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_optimizer_optimizer_proto_init() }
func file_optimizer_optimizer_proto_init() {
	if File_optimizer_optimizer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_optimizer_optimizer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIndexesStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_optimizer_optimizer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIndexesStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_optimizer_optimizer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIndexesStatResponse_IndexStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_optimizer_optimizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optimizer_optimizer_proto_goTypes,
		DependencyIndexes: file_optimizer_optimizer_proto_depIdxs,
		MessageInfos:      file_optimizer_optimizer_proto_msgTypes,
	}.Build()
	File_optimizer_optimizer_proto = out.File
	file_optimizer_optimizer_proto_rawDesc = nil
	file_optimizer_optimizer_proto_goTypes = nil
	file_optimizer_optimizer_proto_depIdxs = nil
}
