// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: optimizer/optimizer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListIndexesStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListIndexesStatRequest) Reset() {
	*x = ListIndexesStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optimizer_optimizer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIndexesStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesStatRequest) ProtoMessage() {}

func (x *ListIndexesStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_optimizer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesStatRequest.ProtoReflect.Descriptor instead.
func (*ListIndexesStatRequest) Descriptor() ([]byte, []int) {
	return file_optimizer_optimizer_proto_rawDescGZIP(), []int{0}
}

type ListIndexesStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListIndexesStatResponse) Reset() {
	*x = ListIndexesStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_optimizer_optimizer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIndexesStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIndexesStatResponse) ProtoMessage() {}

func (x *ListIndexesStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_optimizer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIndexesStatResponse.ProtoReflect.Descriptor instead.
func (*ListIndexesStatResponse) Descriptor() ([]byte, []int) {
	return file_optimizer_optimizer_proto_rawDescGZIP(), []int{1}
}

var File_optimizer_optimizer_proto protoreflect.FileDescriptor

var file_optimizer_optimizer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x69,
	0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x18, 0x0a,
	0x16, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x76, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x41,
	0x50, 0x49, 0x12, 0x66, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65,
	0x73, 0x53, 0x74, 0x61, 0x74, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_optimizer_optimizer_proto_rawDescOnce sync.Once
	file_optimizer_optimizer_proto_rawDescData = file_optimizer_optimizer_proto_rawDesc
)

func file_optimizer_optimizer_proto_rawDescGZIP() []byte {
	file_optimizer_optimizer_proto_rawDescOnce.Do(func() {
		file_optimizer_optimizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_optimizer_optimizer_proto_rawDescData)
	})
	return file_optimizer_optimizer_proto_rawDescData
}

var file_optimizer_optimizer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_optimizer_optimizer_proto_goTypes = []interface{}{
	(*ListIndexesStatRequest)(nil),  // 0: api.optimizer.v1.ListIndexesStatRequest
	(*ListIndexesStatResponse)(nil), // 1: api.optimizer.v1.ListIndexesStatResponse
}
var file_optimizer_optimizer_proto_depIdxs = []int32{
	0, // 0: api.optimizer.v1.OptimizerAPI.ListIndexesStat:input_type -> api.optimizer.v1.ListIndexesStatRequest
	1, // 1: api.optimizer.v1.OptimizerAPI.ListIndexesStat:output_type -> api.optimizer.v1.ListIndexesStatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_optimizer_optimizer_proto_init() }
func file_optimizer_optimizer_proto_init() {
	if File_optimizer_optimizer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_optimizer_optimizer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIndexesStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_optimizer_optimizer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIndexesStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_optimizer_optimizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optimizer_optimizer_proto_goTypes,
		DependencyIndexes: file_optimizer_optimizer_proto_depIdxs,
		MessageInfos:      file_optimizer_optimizer_proto_msgTypes,
	}.Build()
	File_optimizer_optimizer_proto = out.File
	file_optimizer_optimizer_proto_rawDesc = nil
	file_optimizer_optimizer_proto_goTypes = nil
	file_optimizer_optimizer_proto_depIdxs = nil
}
